// <auto-generated />
using System;
using DiaryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiaryApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiaryApp.Models.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Jesus saves me",
                            CreatedAt = new DateTime(2025, 10, 22, 15, 23, 29, 501, DateTimeKind.Local).AddTicks(3814),
                            Title = "Jesus Saves"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Jesus saves me",
                            CreatedAt = new DateTime(2025, 10, 22, 15, 23, 29, 501, DateTimeKind.Local).AddTicks(4473),
                            Title = "Come to Jesus"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Jesus saves me",
                            CreatedAt = new DateTime(2025, 10, 22, 15, 23, 29, 501, DateTimeKind.Local).AddTicks(4475),
                            Title = "All who are heavy laden"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
